import Foundation

/// The words the matcher may never touch, because they are ordinary English.
///
/// **Born 2026-08-27, from two corrupted sentences on the founder's own
/// screen:** "and all of that" landed as "and all of Thota", and "The movie
/// was Marvelously short" landed as "Marvelously Sharat". Both replacements
/// are contact names. Both cleared every existing guard honestly: Double
/// Metaphone reduces each pair to the same key (similarity 1.00, no floor can
/// separate them), the lengths sit inside the 25% tolerance, and the wired
/// earphone mic delivered the low confidence that opens the gate. Sound,
/// length and confidence together cannot tell "short" from "Sharat". Nothing
/// can, acoustically: the difference is that one of them is among the few
/// thousand words a person actually says all day.
///
/// So that difference becomes the guard. A word on this list is never
/// rewritten on sound alone, at any confidence. The cost is measured at
/// zero: every true repair of the 2026-08-15 sweep (Kisu -> Kizu, versal ->
/// Vercel, Challant -> Chalant, Jonalagata -> Jonnalagadda...) has a
/// NON-word on the heard side, which is exactly why they were repairable.
/// When the engine writes a real word for a name ("challenge" for Chalant,
/// "short" for Sharat), the alias path is the door: the user corrects it,
/// the learner records it, and the exact rewrite applies from then on. A
/// guess is not allowed to do what only a correction can justify.
///
/// Lowercase, compared bare. Kept as one flat set so the whole policy is
/// readable in one place and pinned by tests.
enum EverydayWords {

    static func contains(_ word: String) -> Bool {
        words.contains(word.lowercased())
    }

    // ~950 words: function words first, then the everyday content words a
    // person dictates: time, people, work, home, feelings, sizes, colours,
    // and the office vocabulary this app lives inside.
    static let words: Set<String> = [
        // Articles, conjunctions, prepositions, particles
        "a", "an", "the", "and", "or", "but", "nor", "so", "yet", "for", "of",
        "in", "on", "at", "by", "to", "from", "with", "without", "within",
        "into", "onto", "over", "under", "above", "below", "between", "among",
        "through", "during", "before", "after", "around", "about", "against",
        "along", "across", "behind", "beyond", "beside", "besides", "near",
        "off", "out", "up", "down", "past", "since", "until", "till", "upon",
        "toward", "towards", "inside", "outside", "underneath", "via", "per",
        "than", "as", "if", "unless", "because", "although", "though", "while",
        "whereas", "whether", "once", "despite", "except",
        // Pronouns and their contractions
        "i", "me", "my", "mine", "myself", "we", "us", "our", "ours",
        "ourselves", "you", "your", "yours", "yourself", "yourselves", "he",
        "him", "his", "himself", "she", "her", "hers", "herself", "it", "its",
        "itself", "they", "them", "their", "theirs", "themselves", "who",
        "whom", "whose", "which", "what", "this", "that", "these", "those",
        "someone", "somebody", "something", "somewhere", "anyone", "anybody",
        "anything", "anywhere", "everyone", "everybody", "everything",
        "everywhere", "no one", "nobody", "nothing", "nowhere", "one", "ones",
        "i'm", "i'll", "i've", "i'd", "we're", "we'll", "we've", "we'd",
        "you're", "you'll", "you've", "you'd", "he's", "he'll", "he'd",
        "she's", "she'll", "she'd", "it's", "it'll", "it'd", "they're",
        "they'll", "they've", "they'd", "who's", "what's", "that's", "there's",
        "here's", "let's",
        // Auxiliaries, modals, negations
        "am", "is", "are", "was", "were", "be", "been", "being", "do", "does",
        "did", "done", "doing", "have", "has", "had", "having", "will",
        "would", "shall", "should", "can", "could", "may", "might", "must",
        "ought", "need", "dare", "not", "no", "yes", "never", "always",
        "don't", "doesn't", "didn't", "won't", "wouldn't", "shan't",
        "shouldn't", "can't", "cannot", "couldn't", "mayn't", "mightn't",
        "mustn't", "needn't", "isn't", "aren't", "wasn't", "weren't",
        "haven't", "hasn't", "hadn't", "ain't",
        // Question and degree words
        "when", "where", "why", "how", "there", "here", "very", "too", "quite",
        "rather", "really", "just", "only", "even", "also", "still", "almost",
        "enough", "much", "many", "more", "most", "less", "least", "few",
        "fewer", "little", "lot", "lots", "plenty", "several", "some", "any",
        "all", "both", "each", "every", "either", "neither", "none", "such",
        "own", "same", "other", "another", "else", "again", "ever", "often",
        "sometimes", "usually", "rarely", "seldom", "already", "soon", "later",
        "earlier", "early", "late", "now", "then", "today", "tomorrow",
        "yesterday", "tonight", "ago", "yet", "perhaps", "maybe", "probably",
        "definitely", "certainly", "surely", "actually", "basically",
        "honestly", "literally", "seriously", "exactly", "totally",
        "completely", "absolutely", "obviously", "clearly", "apparently",
        "anyway", "anyhow", "instead", "otherwise", "however", "therefore",
        "meanwhile", "moreover", "besides", "indeed", "further", "furthermore",
        "okay", "ok", "alright", "well", "right", "sure", "fine", "please",
        "thanks", "thank", "sorry", "hello", "hey", "hi", "bye", "goodbye",
        // Numbers, order, quantity
        "zero", "one", "two", "three", "four", "five", "six", "seven",
        "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen",
        "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty",
        "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety",
        "hundred", "thousand", "million", "billion", "first", "second",
        "third", "fourth", "fifth", "sixth", "seventh", "eighth", "ninth",
        "tenth", "last", "next", "previous", "half", "quarter", "double",
        "single", "couple", "pair", "dozen", "once", "twice",
        // Time
        "second", "seconds", "minute", "minutes", "hour", "hours", "day",
        "days", "week", "weeks", "weekend", "weekends", "month", "months",
        "year", "years", "decade", "century", "morning", "afternoon",
        "evening", "night", "midnight", "noon", "moment", "moments", "while",
        "time", "times", "date", "dates", "season", "spring", "summer",
        "autumn", "fall", "winter", "monday", "tuesday", "wednesday",
        "thursday", "friday", "saturday", "sunday", "january", "february",
        "march", "april", "may", "june", "july", "august", "september",
        "october", "november", "december", "daily", "weekly", "monthly",
        "yearly", "annual",
        // Common verbs, with the inflections speech actually lands on
        "go", "goes", "going", "gone", "went", "come", "comes", "coming",
        "came", "get", "gets", "getting", "got", "gotten", "make", "makes",
        "making", "made", "take", "takes", "taking", "took", "taken", "give",
        "gives", "giving", "gave", "given", "put", "puts", "putting", "set",
        "sets", "setting", "keep", "keeps", "keeping", "kept", "let", "lets",
        "letting", "say", "says", "saying", "said", "tell", "tells",
        "telling", "told", "speak", "speaks", "speaking", "spoke", "spoken",
        "talk", "talks", "talking", "talked", "ask", "asks", "asking",
        "asked", "answer", "answers", "answered", "call", "calls", "calling",
        "called", "know", "knows", "knowing", "knew", "known", "think",
        "thinks", "thinking", "thought", "thoughts", "believe", "believes",
        "believed", "remember", "remembers", "remembered", "forget",
        "forgets", "forgot", "forgotten", "understand", "understands",
        "understood", "mean", "means", "meaning", "meant", "want", "wants",
        "wanting", "wanted", "wish", "wishes", "wished", "hope", "hopes",
        "hoped", "like", "likes", "liked", "love", "loves", "loved", "hate",
        "hates", "hated", "prefer", "prefers", "preferred", "see", "sees",
        "seeing", "saw", "seen", "look", "looks", "looking", "looked",
        "watch", "watches", "watching", "watched", "hear", "hears", "hearing",
        "heard", "listen", "listens", "listening", "listened", "feel",
        "feels", "feeling", "felt", "touch", "touches", "touched", "find",
        "finds", "finding", "found", "search", "searches", "searched", "lose",
        "loses", "losing", "lost", "use", "uses", "using", "used", "try",
        "tries", "trying", "tried", "work", "works", "working", "worked",
        "play", "plays", "playing", "played", "run", "runs", "running", "ran",
        "walk", "walks", "walking", "walked", "move", "moves", "moving",
        "moved", "stop", "stops", "stopping", "stopped", "start", "starts",
        "starting", "started", "begin", "begins", "beginning", "began",
        "begun", "finish", "finishes", "finished", "end", "ends", "ending",
        "ended", "continue", "continues", "continued", "stay", "stays",
        "stayed", "leave", "leaves", "leaving", "left", "arrive", "arrives",
        "arrived", "return", "returns", "returned", "bring", "brings",
        "bringing", "brought", "carry", "carries", "carried", "send", "sends",
        "sending", "sent", "receive", "receives", "received", "buy", "buys",
        "buying", "bought", "sell", "sells", "selling", "sold", "pay", "pays",
        "paying", "paid", "cost", "costs", "spend", "spends", "spent", "save",
        "saves", "saving", "saved", "open", "opens", "opening", "opened",
        "close", "closes", "closing", "closed", "turn", "turns", "turning",
        "turned", "change", "changes", "changing", "changed", "show", "shows",
        "showing", "showed", "shown", "help", "helps", "helping", "helped",
        "read", "reads", "reading", "write", "writes", "writing", "wrote",
        "written", "type", "types", "typed", "learn", "learns", "learning",
        "learned", "teach", "teaches", "taught", "study", "studies",
        "studied", "live", "lives", "living", "lived", "eat", "eats",
        "eating", "ate", "eaten", "drink", "drinks", "drinking", "drank",
        "sleep", "sleeps", "sleeping", "slept", "wake", "wakes", "woke",
        "sit", "sits", "sitting", "sat", "stand", "stands", "standing",
        "stood", "wait", "waits", "waiting", "waited", "meet", "meets",
        "meeting", "met", "join", "joins", "joined", "follow", "follows",
        "following", "followed", "lead", "leads", "leading", "led", "grow",
        "grows", "growing", "grew", "grown", "build", "builds", "building",
        "built", "break", "breaks", "breaking", "broke", "broken", "fix",
        "fixes", "fixing", "fixed", "cut", "cuts", "cutting", "add", "adds",
        "adding", "added", "remove", "removes", "removed", "check", "checks",
        "checking", "checked", "test", "tests", "testing", "tested", "share",
        "shares", "sharing", "shared", "choose", "chooses", "choosing",
        "chose", "chosen", "decide", "decides", "decided", "plan", "plans",
        "planning", "planned", "happen", "happens", "happened", "seem",
        "seems", "seemed", "appear", "appears", "appeared", "become",
        "becomes", "became", "stay", "matter", "matters", "mattered", "care",
        "cares", "cared", "miss", "misses", "missed", "win", "wins",
        "winning", "won", "fail", "fails", "failed", "pass", "passes",
        "passed", "drop", "drops", "dropped", "pick", "picks", "picked",
        "throw", "throws", "threw", "thrown", "catch", "catches", "caught",
        "hold", "holds", "holding", "held", "pull", "pulls", "pulled",
        "push", "pushes", "pushed", "press", "presses", "pressed", "click",
        "clicks", "clicked", "wear", "wears", "wearing", "wore", "worn",
        "drive", "drives", "driving", "drove", "driven", "ride", "rides",
        "riding", "rode", "fly", "flies", "flying", "flew", "flown", "travel",
        "travels", "traveled", "visit", "visits", "visited", "cook", "cooks",
        "cooking", "cooked", "clean", "cleans", "cleaning", "cleaned", "wash",
        "washes", "washed", "fill", "fills", "filled", "empty", "cover",
        "covers", "covered",
        // Common nouns: people, places, things, work, body, nature
        "person", "people", "man", "men", "woman", "women", "child",
        "children", "kid", "kids", "boy", "boys", "girl", "girls", "baby",
        "family", "families", "parent", "parents", "mother", "mom", "father",
        "dad", "brother", "sister", "son", "daughter", "husband", "wife",
        "friend", "friends", "neighbor", "guy", "guys", "guest", "guests",
        "name", "names", "home", "house", "houses", "room", "rooms", "door",
        "doors", "window", "windows", "wall", "walls", "floor", "floors",
        "roof", "kitchen", "bathroom", "bedroom", "garden", "yard", "garage",
        "school", "schools", "college", "university", "class", "classes",
        "office", "offices", "shop", "shops", "store", "stores", "market",
        "restaurant", "hotel", "hospital", "church", "bank", "banks",
        "airport", "station", "street", "streets", "road", "roads", "city",
        "cities", "town", "towns", "village", "country", "countries",
        "state", "states", "world", "place", "places", "area", "areas",
        "side", "sides", "corner", "top", "bottom", "middle", "center",
        "front", "back", "edge", "point", "points", "line", "lines", "way",
        "ways", "part", "parts", "piece", "pieces", "thing", "things",
        "stuff", "kind", "kinds", "type", "types", "sort", "sorts", "case",
        "cases", "matter", "matters", "fact", "facts", "reason", "reasons",
        "idea", "ideas", "question", "questions", "problem", "problems",
        "issue", "issues", "answer", "answers", "story", "stories", "news",
        "word", "words", "letter", "letters", "sentence", "sentences",
        "message", "messages", "note", "notes", "list", "lists", "page",
        "pages", "book", "books", "paper", "papers", "picture", "pictures",
        "photo", "photos", "video", "videos", "movie", "movies", "film",
        "films", "music", "song", "songs", "game", "games", "sport",
        "sports", "team", "teams", "player", "players", "money", "price",
        "prices", "bill", "bills", "job", "jobs", "career", "business",
        "company", "companies", "customer", "customers", "client", "clients",
        "boss", "manager", "worker", "employee", "employees", "product",
        "products", "service", "services", "project", "projects", "task",
        "tasks", "goal", "goals", "result", "results", "report", "reports",
        "email", "emails", "phone", "phones", "computer", "computers",
        "laptop", "screen", "screens", "keyboard", "mouse", "file", "files",
        "folder", "folders", "document", "documents", "app", "apps",
        "website", "websites", "internet", "link", "links", "account",
        "accounts", "password", "passwords", "number", "numbers", "code",
        "codes", "car", "cars", "bus", "buses", "train", "trains", "plane",
        "planes", "bike", "boat", "ship", "food", "foods", "water", "coffee",
        "tea", "milk", "bread", "meat", "fish", "fruit", "fruits",
        "vegetable", "vegetables", "rice", "egg", "eggs", "cheese", "sugar",
        "salt", "oil", "meal", "meals", "breakfast", "lunch", "dinner",
        "table", "tables", "chair", "chairs", "bed", "beds", "desk", "desks",
        "light", "lights", "clock", "clocks", "watch", "key", "keys", "bag",
        "bags", "box", "boxes", "bottle", "bottles", "cup", "cups", "plate",
        "plates", "glass", "glasses", "clothes", "shirt", "shoes", "hat",
        "coat", "dress", "pocket", "hand", "hands", "arm", "arms", "leg",
        "legs", "foot", "feet", "head", "heads", "face", "faces", "eye",
        "eyes", "ear", "ears", "nose", "mouth", "hair", "heart", "hearts",
        "body", "bodies", "back", "shoulder", "finger", "fingers", "skin",
        "blood", "brain", "voice", "voices", "air", "fire", "earth", "sun",
        "moon", "star", "stars", "sky", "cloud", "clouds", "rain", "snow",
        "wind", "storm", "weather", "sea", "ocean", "river", "rivers",
        "lake", "lakes", "mountain", "mountains", "hill", "hills", "field",
        "fields", "forest", "tree", "trees", "flower", "flowers", "grass",
        "leaf", "leaves", "animal", "animals", "dog", "dogs", "cat", "cats",
        "bird", "birds", "horse", "cow", "health", "doctor", "doctors",
        "medicine", "pain", "life", "lives", "death", "age", "ages", "birth",
        "birthday", "wedding", "party", "parties", "holiday", "holidays",
        "trip", "trips", "vacation", "visit", "visits", "meeting",
        "meetings", "call", "calls", "invoice", "invoices", "order",
        "orders", "payment", "payments", "deal", "deals", "offer", "offers",
        "sale", "sales", "contract", "contracts", "budget", "budgets",
        "schedule", "schedules", "deadline", "deadlines", "update",
        "updates", "version", "versions", "feature", "features", "design",
        "designs", "user", "users", "data", "info", "information", "detail",
        "details", "example", "examples", "level", "levels", "step", "steps",
        "stage", "stages", "process", "processes", "system", "systems",
        "group", "groups", "member", "members", "language", "languages",
        "history", "future", "past", "present", "chance", "chances", "luck",
        "help", "advice", "support", "choice", "choices", "decision",
        "decisions", "difference", "differences", "effect", "effects",
        "cause", "causes", "action", "actions", "situation", "situations",
        "experience", "experiences", "practice", "moment", "value", "values",
        "cost", "quality", "size", "sizes", "shape", "shapes", "color",
        "colors", "colour", "colours", "sound", "sounds", "noise", "smell",
        "taste", "touch", "feeling", "feelings", "emotion", "emotions",
        "truth", "lie", "lies", "joke", "jokes", "fun", "smile", "laugh",
        "cry", "tear", "fear", "worry", "worries", "stress", "peace", "war",
        "law", "laws", "rule", "rules", "right", "rights", "wrong", "power",
        "force", "energy", "speed", "space", "room", "distance", "weight",
        "height", "length", "width", "depth", "amount", "amounts", "total",
        "rest", "break", "breaks", "start", "starts", "beginning", "middle",
        "finish", "review", "reviews", "resume", "resumes",
        // Common adjectives and adverbs
        "good", "better", "best", "bad", "worse", "worst", "great", "nice",
        "fine", "wonderful", "amazing", "awesome", "excellent", "perfect",
        "terrible", "awful", "horrible", "big", "bigger", "biggest", "small",
        "smaller", "smallest", "large", "larger", "largest", "long",
        "longer", "longest", "short", "shorter", "shortest", "tall", "high",
        "higher", "highest", "low", "lower", "lowest", "deep", "wide",
        "narrow", "thick", "thin", "heavy", "light", "fast", "faster",
        "fastest", "slow", "slower", "slowest", "quick", "quickly", "slowly",
        "hard", "harder", "hardest", "soft", "easy", "easier", "easiest",
        "difficult", "simple", "complex", "new", "newer", "newest", "old",
        "older", "oldest", "young", "younger", "youngest", "fresh", "modern",
        "ancient", "recent", "recently", "current", "currently", "hot",
        "hotter", "cold", "colder", "warm", "warmer", "cool", "cooler",
        "dry", "wet", "clean", "dirty", "clear", "dark", "darker", "bright",
        "brighter", "loud", "louder", "quiet", "quieter", "silent", "empty",
        "full", "fuller", "open", "closed", "free", "busy", "cheap",
        "expensive", "rich", "poor", "strong", "stronger", "strongest",
        "weak", "weaker", "healthy", "sick", "ill", "tired", "hungry",
        "thirsty", "happy", "happier", "happiest", "sad", "sadder", "angry",
        "mad", "glad", "excited", "nervous", "afraid", "scared", "proud",
        "surprised", "worried", "bored", "boring", "interesting",
        "interested", "funny", "serious", "strange", "weird", "normal",
        "usual", "common", "rare", "special", "important", "importantly",
        "necessary", "possible", "impossible", "likely", "unlikely",
        "certain", "uncertain", "ready", "able", "unable", "available",
        "different", "similar", "equal", "true", "false", "real", "fake",
        "actual", "main", "major", "minor", "general", "specific",
        "particular", "whole", "entire", "complete", "total", "final",
        "finally", "extra", "additional", "public", "private", "personal",
        "local", "national", "international", "foreign", "global", "central",
        "northern", "southern", "eastern", "western", "left", "right",
        "straight", "round", "square", "flat", "smooth", "rough", "sharp",
        "safe", "dangerous", "careful", "carefully", "beautiful", "pretty",
        "handsome", "ugly", "sweet", "sour", "bitter", "fresh", "delicious",
        "red", "orange", "yellow", "green", "blue", "purple", "pink",
        "brown", "black", "white", "gray", "grey", "gold", "silver",
        "correct", "incorrect", "exact", "wrong", "alone", "together",
        "apart", "away", "close", "far", "further", "nearby", "everywhere",
        "somewhere", "forward", "backward", "ahead", "behind", "aside",
        "upstairs", "downstairs", "outside", "inside", "abroad", "online",
        "offline",
    ]
}
